version: "3"

services:
  mysql:
    build: ./versions/5.7.28
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./tests/fixtures/dataset:/var/lib/mysql/dataset
      - ./tests/fixtures/docker.conf.d:/etc/mysql/docker.conf.d
