#!/bin/sh
set -e

MYSQL_HOST=0.0.0.0

export MYSQL_PWD=${MYSQL_ROOT_PASSWORD}

execute_help () {
    echo "Usage: ... execute QUERY"
    exit
}

execute_wait () {
    echo -n "Service status: " >&2
    while ! mysqladmin -uroot -h${MYSQL_HOST} -s ping >&2; do sleep 1; done && true
    return 0
}

[ -z "$1" ] && execute_help

execute_wait

mysql -B -uroot -h${MYSQL_HOST} "${MYSQL_DATABASE}" -e "$1"
