FROM mysql:%{version}

RUN mkdir /var/lib/mysql-dataset /etc/mysql/docker.conf.d && \
    echo "!includedir /etc/mysql/docker.conf.d/" >> /etc/mysql/my.cnf

COPY dataset execute docker-entrypoint.sh /usr/local/bin/

