FROM mysql:%{version}

COPY dataset execute inherit-entrypoint.sh /usr/local/bin/

RUN mkdir /etc/docker.d/ /etc/mysql/docker.conf.d/ && echo "!includedir /etc/mysql/docker.conf.d/" >> /etc/mysql/my.cnf

mkdir -p /var/lib/mysql/dataset && echo "$@" >> /var/lib/mysql/dataset/test.log

#ENTRYPOINT ["inherit-entrypoint.sh"]
